# the user and world volume are setup for truenas

services:
  atm9:
    image: itzg/minecraft-server:java17
    container_name: atm9
    restart: unless-stopped
    user: 568:568
    ports:
      - 25565:25565
      - 8123:8123
    environment:
      EULA: "true"
      DUMP_SERVER_PROPERTIES: "true"
      TYPE: AUTO_CURSEFORGE
      CF_SLUG: all-the-mods-9
      CF_API_KEY: ${CF_API_KEY}
      ICON: https://media.forgecdn.net/avatars/thumbnails/902/338/64/64/638350403793040080.png
      MEMORY: 16G
      MAX_PLAYERS: "20"
      MOTD: |
        A %TYPE% server on %VERSION%
        running %MODPACK_NAME% %MODPACK_VERSION%
      DIFFICULTY: normal
      OPS: 0ctobogs
      SPAWN_PROTECTION: "0"
      ENABLE_RCON: "false"
      ALLOW_FLIGHT: "true"
      ENABLE_COMMAND_BLOCK: "true"
      TZ: America/Chicago
      CURSEFORGE_FILES: |
        dynmapforge@3.6
      MODS: "/extras/DynmapBlockScan-3.6-forge-1.20.jar"
      # temp disable for very long initial startups
      MAX_TICK_TIME: "-1"
    volumes:
      - /mnt/fast/minecraft/atm9:/data
      - /mnt/fast/minecraft/extras:/extras:ro
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
networks: {}

# https://console.curseforge.com/#/api-keys
# .env
# CF_API_KEY='$2a$10$...'
